version: '3'

services:
  frontend:
    build:
      context: ./portfolio-angular  # Specify the correct path to the frontend Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Specify the correct path to the backend Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/mentalHealthApp
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
