services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "4200:80" # Maps Angular app to port 4200
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000" # Maps backend to port 5000
    environment:
      MONGO_URI: mongodb://mongo:27017/mentalHealthApp
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
