services:
  frontend:
    build:
      context: ./portfolio-angular
      args:
        - API_URL=http://backend:3000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mentalHealthApp
      - PORT=3001
      - EMAIL_USER=mariejuly70@gmail.com
      - EMAIL_PASS=xcusybymihabpowh

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
